//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmericaVirtual_Web.AmericaeReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AmericaeReference.IAmericaVirtualService")]
    public interface IAmericaVirtualService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmericaVirtualService/GetData", ReplyAction="http://tempuri.org/IAmericaVirtualService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmericaVirtualService/GetData", ReplyAction="http://tempuri.org/IAmericaVirtualService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmericaVirtualService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAmericaVirtualService/GetDataUsingDataContractResponse")]
        AmericaVirtualWS.CompositeType GetDataUsingDataContract(AmericaVirtualWS.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmericaVirtualService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAmericaVirtualService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<AmericaVirtualWS.CompositeType> GetDataUsingDataContractAsync(AmericaVirtualWS.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmericaVirtualService/ValidateLogin", ReplyAction="http://tempuri.org/IAmericaVirtualService/ValidateLoginResponse")]
        bool ValidateLogin(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmericaVirtualService/ValidateLogin", ReplyAction="http://tempuri.org/IAmericaVirtualService/ValidateLoginResponse")]
        System.Threading.Tasks.Task<bool> ValidateLoginAsync(string user, string pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAmericaVirtualServiceChannel : AmericaVirtual_Web.AmericaeReference.IAmericaVirtualService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AmericaVirtualServiceClient : System.ServiceModel.ClientBase<AmericaVirtual_Web.AmericaeReference.IAmericaVirtualService>, AmericaVirtual_Web.AmericaeReference.IAmericaVirtualService {
        
        public AmericaVirtualServiceClient() {
        }
        
        public AmericaVirtualServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AmericaVirtualServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AmericaVirtualServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AmericaVirtualServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public AmericaVirtualWS.CompositeType GetDataUsingDataContract(AmericaVirtualWS.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<AmericaVirtualWS.CompositeType> GetDataUsingDataContractAsync(AmericaVirtualWS.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public bool ValidateLogin(string user, string pass) {
            return base.Channel.ValidateLogin(user, pass);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateLoginAsync(string user, string pass) {
            return base.Channel.ValidateLoginAsync(user, pass);
        }
    }
}
